export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex items-center justify-center mx-auto min-h-screen'>
        {children}
      </body>
    </html>
  );
}
